# Generated by Django 5.1.4 on 2024-12-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_booking_user_alter_booking_number_of_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Kitchen', 'Kitchen'), ('Service', 'Service'), ('Management', 'Management'), ('Front Desk', 'Front Desk')], default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
